<section class="page-section clearfix">
    <div class="container col-md-5">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
            <h2 class="section-heading mb-4">
                <span class="section-heading-upper">
                    <a href="<?= $this->apiUrl ?>/goodest_boi?id_doggo=<?= $good_boi-> ID ?>">
                        <?= $good_boi -> Nome ?> | <?= $good_boi -> Raca ?>
                    </a>
                </span>
                <span class="section-heading-lower"><?= $good_boi -> Idade ?> anos</span>
            </h2>
            <p class="mb-3"> <?= $good_boi -> Descricao ?></p>
            <div class="intro-button mx-auto">
                <a class="btn btn-primary btn-xl" href="<?= $this->apiUrl ?>/adota_doggo?id_doggo=<?= $good_boi-> ID ?>">Me Adote</a>
                <a class="btn btn-primary btn-xl" href="<?= $this->apiUrl ?>/atualiza_doggo?id_doggo=<?= $good_boi-> ID ?>">Atualizar</a>
            </div>
        </div>
    </div>
</section>