<div class="container">
    <div class="Adocao mb-4">
        <div class="body-form space-around">
            <h1 class="pt-4">Cadastre um goodest boi :)</h1>
            <form action="<?= $this->apiUrl ?>/api/inserir_doggo" id="opdg" method="post">
                <div class="form-row">
                    <div class="form-group col-lg-10">
                        <label for="Nome">Nome do Doggo</label>
                        <input type="text" class="form-control" id="Nome" name="Nome">
                    </div>
                    <div class="form-group col-lg-2">
                        <label for="Idade">Idade</label>
                        <input type="number" min="1" max="25"class="form-control" id="Idade" name="Idade">
                    </div>
                    <div class="form-group col-lg-6">
                        <label for="Raca">Raça</label>
                        <input type="text" class="form-control" id="Raca" name="Raca">
                    </div>
                    <div class="form-group col-lg-12">
                        <label for="Descricao">Descrição</label>
                        <textarea form="opdg" class="form-control" rows="10" id="Descricao" name="Descricao"></textarea>
                    </div>
                </div>
                <button type="submit" value="inserir_doggo" class="btn btn-primary botao">Adotar</button><br/>
                <small class="text-muted">espero que seja um bom motivo</small>
            </form>
        </div>
    </div>
</div>
