<h2>Atualizar Usuário</h2>
<form action="<?= $this->apiUrl ?>/api/atualizaUsuario" method="post">
    <input type="hidden" name="idUsuario" class="idUsuario" value="<?= $usuario->id ?>">
    <div class="col-md-6 mb-3">
        <label for="nomeUsuario">Nome do Usuário</label>
        <input type="text" class="form-control" id="nomeUsuario" name="nomeUsuario" required="false" value="<?= $usuario->nome ?>">
    </div>
    <div class="col-md-6 mb-3">
        <label for="emailUsuario">E-mail</label>
        <input type="email" class="form-control" id="emailUsuario" name="emailUsuario" required="false" value="<?= $usuario->email ?>">
    </div>
    <div class="col-md-6 mb-3">
        <label for="loginUsuario">Login</label>
        <input type="text" class="form-control" id="loginUsuario" name="loginUsuario" required="false" value="<?= $usuario->login ?>">
    </div>
    <div class="col-md-6 mb-3">
        <label for="senhaUsuario">Senha</label>
        <input type="password" class="form-control" id="senhaUsuario" name="senhaUsuario" required="false" value="<?= $usuario->login ?>">
    </div>
    <input type="submit" value="Atualizar">
</form>


