<h2>Atualizar Patrimônio</h2>
<form action="<?= $this->apiUrl ?>/api/atualizaPatrimonio" method="post">
    <input type="hidden" name="idPatrimonio" class="idPatrimonio" value="<?= $patrimonio->id ?>">
    <div class="col-md-6 mb-3">
        <label for="descricaoPatrimonio">Descrição</label>
        <input type="text" class="form-control" id="descricaoPatrimonio" name="descricaoPatrimonio" required="true" value="<?= $patrimonio->descricao ?>">
    </div>
    <div class="col-md-6 mb-3">
        <label for="dataDeInclusao">Data de inclusão</label>
        <input type="date" class="form-control" id="dataDeInclusao" name="dataDeInclusao" required="true" value="<?= $patrimonio->dataDeInclusao ?>">
    </div>
    <div class="col-md-6 mb-3">
        <label for="status">Status</label>
        <input type="text" class="form-control" id="status" name="status" required="true" value="<?= $patrimonio->status ?>">
    </div>
    <input type="submit" value="Atualizar">
</form>


