<h2>Cadastrar Usuário</h2>
<form action="<?= $this->apiUrl ?>/api/cadastraUsuario" method="post">
    <div class="col-md-6 mb-3">
        <label for="nomeUsuario">Nome do usuário</label>
        <input type="text" class="form-control" id="nomeUsuario" name="nomeUsuario" required="true">
    </div>
    <div class="col-md-6 mb-3">
        <label for="emailUsuario">E-mail</label>
        <input type="text" class="form-control" id="emailUsuario" name="emailUsuario" required="true">
    </div>
    <div class="col-md-6 mb-3">
        <label for="loginUsuario">Login</label>
        <input type="text" class="form-control" id="loginUsuario" name="loginUsuario" required="true">
    </div>
    <div class="col-md-6 mb-3">
        <label for="senhaUsuario">Senha</label>
        <input type="password" class="form-control" id="senhaUsuario" name="senhaUsuario" required="true">
    </div>
    <input type="submit" value="Cadastrar">
</form>
