<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Home</title>

        <!-- Bootstrap -->
        <link href="bootstrap-4.1.3-dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://kit.fontawesome.com/37576e6e1c.js" crossorigin="anonymous"></script>
        <link href="view/css/home.css" rel="stylesheet"></link>
    </head>
    <body>

        <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
            <span class="navbar-brand col-sm-3 col-md-2 mr-0" href="#">Nome da companhia</span>
            <!-- <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search"> -->
            <ul class="navbar-nav px-3">
                <li class="nav-item text-nowrap">
                    <a class="nav-link" href="<?= $this->apiUrl ?>/sair">Sair</a>
                </li>
            </ul>
        </nav>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="sidebar-sticky">
                        <ul class="nav flex-column">
                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-3 mb-1 text-muted">
                                <span>Patrimônios</span>
                            </h6>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->apiUrl ?>/home">
                                    <span class="fas fa-home"></span>
                                    Home <span class="sr-only">(atual)</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="<?= $this->apiUrl ?>/cadastrar-patrimonio">
                                    <span class="fas fa-cogs cogs-icon"></span>
                                    Cadastro
                                </a>
                            </li>
                        </ul>

                        <ul class="nav flex-column">
                            <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                                <span>Usuários</span>
                            </h6>

                            <li class="nav-item">
                            <a class="nav-link" href="<?= $this->apiUrl ?>/usuarios">
                                    <span class="fas fa-user-edit"></span>
                                    Listar usuários
                                </a>
                            </li>

                            <li class="nav-item">
                            <a class="nav-link" href="<?= $this->apiUrl ?>/cadastrar-usuario">
                                    <span class="fas fa-user-edit"></span>
                                    Cadastro
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>

                <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
                    <?php include $this->content ?>
                </main>
            </div>
        </div>
    </body>
</html>