<?php if($this->msg == "sucesso-cadastrar-usuario") { ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert" id="alert">
    Usuário cadastrado com sucesso!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<?php } ?>  

<?php if($this->msg == "erro-cadastrar-usuario") { ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert" id="alert">
    Erro ao cadastrar usuário!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<?php } ?>

<?php if($this->msg == "sucesso-atualizar-usuario") { ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert" id="alert">
    Usuário atualizado com sucesso!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<?php } ?>  

<?php if($this->msg == "erro-atualizar-usuario") { ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert" id="alert">
    Erro ao atualizar usuário!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<?php } ?>

<?php if($this->msg == "sucesso-excluir-usuario") { ?>
    <div class="alert alert-success alert-dismissible fade show" role="alert" id="alert">
    Usuário excluído com sucesso!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<?php } ?>  

<?php if($this->msg == "erro-excluir-usuario") { ?>
    <div class="alert alert-danger alert-dismissible fade show" role="alert" id="alert">
    Erro ao excluir usuário!
    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
<?php } ?>

<h2>Lista de Usuários Cadastrados</h2>
<div class="table-responsive">
    <table class="table table-striped table-sm">
    <thead>
        <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Login</th>
        <th></th>
        <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($lista as $item) { ?>
            <tr>
            <td><?= $item->nome ?></td>
            <td><?= $item->email ?></td>
            <td><?= $item->login ?></td>
            <td><a class="far fa-edit" href="<?= $this->apiUrl ?>/atualizar-usuario?id=<?= $item->id ?>"></a></td>
            <td><a class="far fa-trash-alt" href="<?= $this->apiUrl ?>/deletar-usuario?id=<?= $item->id ?>"></a></td>
            </tr>
        <?php } ?>
    </tbody>
    </table>
</div>
