<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Login</title>

        <!-- Bootstrap -->
        <link href="bootstrap-4.1.3-dist/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://kit.fontawesome.com/37576e6e1c.js" crossorigin="anonymous"></script>
        <link href="view/css/login.css" rel="stylesheet"></link>
    </head>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-4 offset-md-4">
                <?php if($this->msg == "erro-login") { ?>
                    <div class="alert alert-danger alert-dismissible fade show" role="alert" id="alert">
                    Erro ao fazer login!
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close" onclick="document.getElementById('alert').style.display = 'none'">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                <?php } ?>
                    <form class="form-signin" action="<?= $this->apiUrl ?>/fazer-login" method="post">
                        <div class="text-center mb-4">
                            <div>
                                <span class="fas fa-cogs cogs-icon" ></span>
                            </div>
                          <h1 class="h3 mb-3 font-weight-normal">Gerenciador de Patrimônio</h1>
                        </div>
                
                        <div class="form-group">
                        <input type="text" id="inputLogin" name="inputLogin" class="form-control" placeholder="Login" required="true" autofocus="">
                        </div>
                
                        <div class="form-group">
                        <input type="password" id="inputPassword" name="inputPassword" class="form-control" placeholder="Senha" required="">
                        </div>
                
                        <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="lembrar de mim"> Lembrar de mim
                        </label>
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
                        <p class="mt-5 mb-3 text-muted text-center">© 2019</p>
                    </form>
                </div>
            </div>
        </div>

        <!-- jQuery (obrigatório para plugins JavaScript do Bootstrap) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <!-- Inclui todos os plugins compilados (abaixo), ou inclua arquivos separadados se necessário -->
        <script src="bootstrap-4.1.3-dist/js/bootstrap.min.js"></script>
    </body>
</html>